### ISSUE TITLE
[bitnami/airflow] UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 128: ordinal not in range(128)

### ISSUE THREAD

**Issue by mustela** [bitnami/bitnami-docker-airflow#24]
Hey there! Im moving this issue here, since is not a "problem" with the chart but with the image

https://github.com/bitnami/charts/issues/1845

Im having a hard time with logging.info. Im moving things from a pg db into another pg db using the PostgresHook. And when inserting the record into the second db, Im having the following error:

```
[2020-01-21 22:49:09,556] {logging_mixin.py:112} WARNING - --- Logging error ---
[2020-01-21 22:49:09,557] {logging_mixin.py:112} WARNING - Traceback (most recent call last):
[2020-01-21 22:49:09,557] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/python/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
[2020-01-21 22:49:09,557] {logging_mixin.py:112} WARNING - UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 128: ordinal not in range(128)
[2020-01-21 22:49:09,557] {logging_mixin.py:112} WARNING - Call stack:
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/bin/airflow", line 37, in <module>
    args.func(args)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 545, in run
    _run(args, dag, ti)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 460, in _run
    run_job.run()
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/jobs/base_job.py", line 221, in run
    self._execute()
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/jobs/local_task_job.py", line 95, in _execute
    self.task_runner.start()
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 41, in start
    self.process = self._start_by_fork()
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 80, in _start_by_fork
    args.func(args)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/cli.py", line 75, in wrapper
    return f(*args, **kwargs)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 545, in run
    _run(args, dag, ti)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/bin/cli.py", line 465, in _run
    pool=args.pool,
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
[2020-01-21 22:49:09,559] {logging_mixin.py:112} WARNING -   File "/opt/bitnami/airflow/venv/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 955, in _run_raw_task
    result = task_copy.execute(context=context)

```

As you can see here, before inserting it tries to logs the query and params. And that's where it's failing, because one of my params contains this string "1.5 Inch Ombré Satin Wired Ribbon - WX45 - RED/GREEN"

If you try to logging it directly into any dag like `logging.info("1.5 Inch Ombré Satin Wired Ribbon - WX45 - RED/GREEN")` you will have the error.

Im wondering if this something around not how these chart containers are being generated (maybe with some missing encoding) or something else.

You can run a container and run the following
```
airflow@airflow-web-8bfb4589b-lqcxv:/$ python
Python 3.6.10 (default, Dec 19 2019, 04:04:42) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.info("1.5 Inch Ombré Satin Wired Ribbon - WX45 - RED/GREEN")
  File "<stdin>", line 0
    
    ^
SyntaxError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)
>>> 
If I run python3 -c 'import sys; print(sys.stdout.encoding)' I get ANSI_X3.4-1968, that obviusly does not support those type of characters é`.
```

So if I run that in another python3 default container, I can see that it's set to UTF-8

Im checking this image https://github.com/puckel/docker-airflow/, which works just fine, and comparing with yours the most visible difference is around locale https://github.com/puckel/docker-airflow/blob/master/Dockerfile#L21, Ive set all those vars but still same result. So maybe something around this https://github.com/puckel/docker-airflow/blob/master/Dockerfile#L53

Any idea? Thanks!

**Comment by mustela** [comment]
So the image with these changes seems to be working https://github.com/bitnami/bitnami-docker-airflow/compare/master...mustela:master

**Comment by juan131** [comment]
Hi @mustela 

Thanks so much for reporting this issue! As you mentioned it's a problem with the locale settings.

```diff
< RUN install_packages ca-certificates curl dirmngr gnupg libbsd0 libbz2-1.0 libc6 libcomerr2 libedit2 libffi6 libgcc1 libgmp10 libgnutls30 libgssapi-krb5-2 libhogweed4 libicu57 libidn11 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 liblzma5 libmariadbclient18 libncurses5 libnettle6 libnss-wrapper libp11-kit0 libreadline7 libsasl2-2 libsqlite3-0 libssl1.1 libstdc++6 libtasn1-6 libtinfo5 libuuid1 libxml2 libxslt1.1 procps sudo unzip zlib1g
---
> RUN install_packages ca-certificates curl dirmngr gnupg libbsd0 libbz2-1.0 libc6 libcomerr2 libedit2 libffi6 libgcc1 libgmp10 libgnutls30 libgssapi-krb5-2 libhogweed4 libicu57 libidn11 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 liblzma5 libmariadbclient18 libncurses5 libnettle6 libnss-wrapper libp11-kit0 libreadline7 libsasl2-2 libsqlite3-0 libssl1.1 libstdc++6 libtasn1-6 libtinfo5 libuuid1 libxml2 libxslt1.1 locales procps sudo unzip zlib1g
18a19
> RUN localedef -c -f UTF-8 -i en_US en_US.UTF-8
19a21,23
> RUN update-locale LANG=C.UTF-8 LC_MESSAGES=POSIX && \
>     DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
> RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen
44a49,50
>     LANG="en_US.UTF-8" \
>     LANGUAGE="en_US:en" \
```

I'm working on adding these change to our image that should fix the issue ⏫

**Comment by juan131** [comment]
Hi @mustela 

A new docker image has been released including the right locale settings (see https://github.com/bitnami/bitnami-docker-airflow/blob/master/1/debian-10/Dockerfile#L19)
Please note this image is based on `debian 10` "buster" (instead of `debian 9`) since we're moving the whole catalog from `debian-9` to `debian-10`.

Could you give it a try? The image tag is `1.10.7-debian-10-r0`

**Comment by mustela** [comment]
Oh that's quite a change :) but give me some time and Ill def give it a try! Thanks a lot!

**Comment by mustela** [comment]
@juan131 there is still an issue, you can easily test it running a container -> python and try to log some string like: 

```
airflow@airflow-worker-0:/$ python
Python 3.6.10 (default, Jan 23 2020, 23:14:18) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.info("1.5 Inch Ombré Satin Wired Ribbon - WX45 - RED/GREEN")
  File "<stdin>", line 0
    
    ^
SyntaxError: 'ascii' codec can't decode byte 0xc3 in position 27: ordinal not in range(128)
>>> 
```

**Comment by mustela** [comment]
Also, if you run `locale` inside the container you will see
```
airflow@airflow-worker-0:/$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8bitnami-docker-airflow-worker
```

While using the changes I presented you will get:
```
airflow@airflow-worker-0:/$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by juan131** [comment]
Hi @mustela 

What version of Airflow are you using? I'm not able to reproduce the issue...

```bash
$ docker run --rm -it bitnami/airflow:1.10.7-debian-10-r0 bash
...
Welcome to the Bitnami airflow container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow/issues
Send us your feedback at containers@bitnami.com
...
I have no name!@1e21e94a4eae:/$ python
Python 3.6.10 (default, Jan 23 2020, 23:14:18)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> logging.info("1.5 Inch Ombré Satin Wired Ribbon - WX45 - RED/GREEN")
>>> exit()
I have no name!@1e21e94a4eae:/$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by mustela** [comment]
@juan131 sorry for my very late reply, but the problem is in the worker, the web image has been fixed, but Check this out: 

docker run --rm -it bitnami/airflow-worker:1.10.7-debian-10-r0 bash
```
NWRAP_ERROR(1) - nwrap_files_cache_reload: Unable to open '/opt/bitnami/airflow/nss_passwd' readonly -1:No such file or directory
NWRAP_ERROR(1) - nwrap_files_getpwuid: Error loading passwd file

Welcome to the Bitnami airflow-worker container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-airflow-worker
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-airflow-worker/issues
Send us your feedback at containers@bitnami.com

NWRAP_ERROR(8) - nwrap_files_cache_reload: Unable to open '/opt/bitnami/airflow/nss_passwd' readonly -1:No such file or directory
NWRAP_ERROR(8) - nwrap_files_getpwuid: Error loading passwd file
I have no name!@e01d01248189:/$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
I have no name!@e01d01248189:/$
````

**Comment by mustela** [comment]
Happens the same with `1.10.7-ol-7-r38`

**Comment by juan131** [comment]
Hi @mustela 

It looks i fixed the issue on `bitnami/airflow` but forgot about `/bitnami/airflow-worker`. Sorry my fault

I'll apply the same fix and ping you once we released the new image.

**Comment by juan131** [comment]
Hi @mustela 

I just released a new version `bitnami/airflow-worker:1.10.7-debian-10-r11`. Could you give it a try?

**Comment by mustela** [comment]
@juan131, it's working beautiful! :) 

Thanks a lot for your help! Will close this one ✔️

**Comment by juan131** [comment]
I'm glad to heart that!
Thanks to you for reporting it!!
